# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc:latest

# setting env variables
variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt update && apt -y install cmake libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev ninja-build
  script:
    - mkdir build && cd build
    - cmake .. -G"Ninja" -DOpenGL_GL_PREFERENCE=GLVND
    - ninja && ninja install
    - cd ..
  artifacts:
    paths:
      - bin/

# depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
cache:
  paths:
    - vendor/

# run tests using the binary built before
test:
  stage: test
  script:
    - ./bin/myapp
