version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\cmake-starter-project
image:
- Visual Studio 2019
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: x64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019" )
- echo %generator%

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator%

build:
  project: c:\projects\cmake-starter-project\build\MyProject.sln
  verbosity: minimal
  parallel: true
