version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run: 'apt-get update && apt-get install -y git'
      - run: 'apt-get update && apt-get install -y gcc g++'
      - run: 'apt-get update && sudo apt-get install -y cmake'
      - run: 'git submodule sync && git submodule update --init'
      - run: 'cmake .'
      - run: 'make'
      - run: './bin/myapp'
#  test:
#    docker:
#      - image: ubuntu:latest
#    steps:
#      - checkout
#      - run: git submodule sync
#      - run: git submodule update --init    
#      - run: cmake -H. -Bbuild
#      - run: cmake --build build
workflows:
  version: 2
  build:
    jobs:
      - build
