name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      ###########
      ## Debug ##
      ###########
      - name: Create Build Environment [Debug]
        run: cmake -E make_directory ${{ runner.workspace }}/build-Debug

      - name: Configure CMake [Debug]
        shell: bash
        working-directory: ${{ runner.workspace }}/build-Debug
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug

      - name: Build [Debug]
        working-directory: ${{ runner.workspace }}/build-Debug
        shell: bash
        run: cmake --build . --config Debug

      - name: Cache Build [Debug]
        uses: actions/cache@v2
        with:
          path: |
            ${{ runner.workspace }}/build-Debug
          key: ${{ matrix.os }}-build-Debug-${{ github.sha }}
          restore-keys: |
            ${{ matrix.os }}-build-Debug-${{ github.sha }}

      #############
      ## Release ##
      #############
      - name: Create Build Environment [Release]
        run: cmake -E make_directory ${{ runner.workspace }}/build-Release

      - name: Configure CMake [Release]
        shell: bash
        working-directory: ${{ runner.workspace }}/build-Release
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

      - name: Build [Release]
        working-directory: ${{ runner.workspace }}/build-Release
        shell: bash
        run: cmake --build . --config Release

      - name: Cache Build [Release]
        uses: actions/cache@v2
        with:
          path: |
            ${{ runner.workspace }}/build-Release
          key: ${{ matrix.os }}-build-Release-${{ github.sha }}
          restore-keys: |
            ${{ matrix.os }}-build-Release-${{ github.sha }}

  test:
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        config: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
      ###########
      ## Debug ##
      ###########
      - name: Cache Build [Debug]
        uses: actions/cache@v2
        with:
          path: |
            ${{ runner.workspace }}/build-Debug
          key: ${{ matrix.os }}-build-Debug-${{ github.sha }}
          restore-keys: |
            ${{ matrix.os }}-build-Debug-${{ github.sha }}

      - name: Test [Debug]
        working-directory: ${{ runner.workspace }}/build-Debug
        shell: bash
        run: ctest . -C Debug

      #############
      ## Release ##
      #############
      - name: Cache Build [Release]
        uses: actions/cache@v2
        with:
          path: |
            ${{ runner.workspace }}/build-Release
          key: ${{ matrix.os }}-build-Release-${{ github.sha }}
          restore-keys: |
            ${{ matrix.os }}-build-Release-${{ github.sha }}

      - name: Test [Release]
        working-directory: ${{ runner.workspace }}/build-Release
        shell: bash
        run: ctest . -C Release
