name: build

on: [push]

env:
  CMAKE_CONFIG_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Create Build Environment
        run: cmake -E make_directory ${{ runner.workspace }}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{ runner.workspace }}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: cmake --build . --config ${{ env.CMAKE_CONFIG_TYPE }}

      ###########
      ## Cache ##
      ###########
      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: |
            ${{ runner.workspace }}/build
          key: ${{ matrix.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ matrix.os }}-build-${{ github.sha }}

  test:
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      ###########
      ## Cache ##
      ###########
      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: |
            ${{ runner.workspace }}/build
          key: ${{ matrix.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ matrix.os }}-build-${{ github.sha }}

      ##########
      ## Test ##
      ##########
      - name: Test
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: ctest . -C ${{ env.CMAKE_CONFIG_TYPE }}
